image: denoland/deno:1.11.0

stages:
  - test
  - setup
  - build

cache:
  paths:
    - .npm/
    - node_modules/

setup:
  stage: setup
  image: node:16-alpine
  script:
    - npm ci --cache .npm --prefer-offline

test:
  stage: test
  script:
    - deno lint --ignore=node_modules,dist
    - deno test --unstable --allow-net *.test.ts

build:
  stage: build
  script:
    - deno run --unstable --allow-read=. --allow-write=dist _build.ts
